extends Node
class_name Enums

enum TrainDirection {
    NORTH_FOLLOWING,
    SOUTH_FOLLOWING,
    EAST_FOLLOWING,
    WEST_FOLLOWING,
    NORTH_OPPOSING,
    SOUTH_OPPOSING,
    EAST_OPPOSING,
    WEST_OPPOSING
}

enum TrackSegmentType {
    REGULAR_TRACK_SEGMENT,
    SINGULAR_TRACK_SEGMENT,
    STATION_TRACK_SEGMENT,
    SWITCHING_TRACK_SEGMENT
}

enum RegularTrackSegment {
    EAST_TO_WEST,
    NORTH_TO_SOUTH,
    NORTH_TO_EAST,
    NORTH_TO_WEST,
    SOUTH_TO_EAST,
    SOUTH_TO_WEST,
    EAST_ENTRY_REVERSING,
    NORTH_ENTRY_REVERSING,
    SOUTH_ENTRY_REVERSING,
    WEST_ENTRY_REVERSING
}

enum SingularTrackSegment {
    HORIZONTAL_FOLLOWING_TO_OPPOSING,
    HORIZONTAL_OPPOSING_TO_FOLLOWING,
    VERTICAL_FOLLOWING_TO_OPPOSING,
    VERTICAL_OPPOSING_TO_FOLLOWING
}

enum StationTrackSegment {
    HORIZONTAL_THROUGH,
    VERTICAL_THROUGH,
    EAST_ENTRY_TERMINATING,
    NORTH_ENTRY_TERMINATING,
    SOUTH_ENTRY_TERMINATING,
    WEST_ENTRY_TERMINATING
}

enum SwitchingTrackSegment {
    EAST_TO_WEST_AND_NORTH_TO_EAST,
    EAST_TO_WEST_AND_NORTH_TO_WEST,
    EAST_TO_WEST_AND_SOUTH_TO_EAST,
    EAST_TO_WEST_AND_SOUTH_TO_WEST,
    NORTH_TO_SOUTH_AND_NORTH_TO_EAST,
    NORTH_TO_SOUTH_AND_NORTH_TO_WEST,
    NORTH_TO_SOUTH_AND_SOUTH_TO_EAST,
    NORTH_TO_SOUTH_AND_SOUTH_TO_WEST,
    HORIZONTAL_DOUBLE_CROSSOVER,
    VERTICAL_DOUBLE_CROSSOVER
}

enum RelativePosition {
    NORTH,
    SOUTH,
    EAST,
    WEST
}